### ISSUE TITLE
Fix code scanning alert - Database query built from user-controlled sources

### ISSUE THREAD

**Issue by fufeck** [BaseAdresseNationale/api-signalement#1]
## Modification

- Rajouter @isMongoId a UpdateSignalementDTO.id

Tracking issue for:
- [x] https://github.com/BaseAdresseNationale/api-signalement/security/code-scanning/1
- [x] https://github.com/BaseAdresseNationale/api-signalement/security/code-scanning/2

**Comment by MaGOs92** [comment]
Done
